# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sample_analytics'
config-version: 2
version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config states that models in this project can be found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Specify target and clean paths
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "logs"

# Retrieve our env vars into project variables
vars:
  stage: "{{ env_var('DBT_STAGE', 'default_stage') }}"
  instance: "{{ env_var('DBT_INSTANCE', 'default_instance') }}"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configure-your-project/
models:
  sample_analytics:
    staging:
      +enabled: true
      +materialized: incremental
      +incremental_strategy: append # Specify the strategy for incremental models
      +bind: false # all views defined as late-binding, unless overridden by a model-specific config

# Configuring seeds
seeds:
  sample_analytics:
    +enabled: true
    +schema: staging
    +quote_columns: false # Adding quote_columns for better flexibility

# Quoting configurations
quoting:
  database: false
  schema: true
  identifier: true
